# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o data.o quickslot.o
LINKOBJ  = main.o data.o quickslot.o
LIBS     = -L"E:/DevTools/Dev-Cpp/MinGW64/lib" -L"E:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"E:/DevTools/Dev-Cpp/MinGW64/customlib" -L"E:/DevTools/Dev-Cpp/MinGW64/opengl" -static-libgcc -ldoublebuffer
INCS     = -I"E:/DevTools/Dev-Cpp/MinGW64/include" -I"E:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/DevTools/Dev-Cpp/MinGW64/customlib" -I"E:/DevTools/Dev-Cpp/MinGW64/opengl"
CXXINCS  = -I"E:/DevTools/Dev-Cpp/MinGW64/include" -I"E:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"E:/DevTools/Dev-Cpp/MinGW64/opengl"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

data.o: data.c
	$(CC) -c data.c -o data.o $(CFLAGS)

quickslot.o: quickslot.c
	$(CC) -c quickslot.c -o quickslot.o $(CFLAGS)
