# Project: Program_Quickslot
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o data.o quickslot.o ctrls.o
LINKOBJ  = main.o data.o quickslot.o ctrls.o
LIBS     = -L"D:/DevTools/Dev-Cpp/MinGW64/lib" -L"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2" -static-libgcc -L"D:/GitHub/Program_Quickslot/lib" -mwindows -ldoublebuffer -lpsapi -lstrproc2 -lctrlmanager
INCS     = -I"D:/DevTools/Dev-Cpp/MinGW64/include" -I"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/GitHub/Program_Quickslot/header"
CXXINCS  = -I"D:/DevTools/Dev-Cpp/MinGW64/include" -I"D:/DevTools/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DevTools/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"D:/GitHub/Program_Quickslot/header"
BIN      = Program_Quickslot.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

data.o: data.c
	$(CC) -c data.c -o data.o $(CFLAGS)

quickslot.o: quickslot.c
	$(CC) -c quickslot.c -o quickslot.o $(CFLAGS)

ctrls.o: ctrls.c
	$(CC) -c ctrls.c -o ctrls.o $(CFLAGS)
